title: Guidance on Therapeutic Product Registration in Singapore
remote_theme: opendocsg/opendoc-theme
repository: opendocsg/opendoc-template
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
section_order:
  - Therapeutic Products Guidance
plugins:
  -  jekyll-include-cache
styling_options:
  primary_brand_color: '#444'
  logo_path: /assets/logo.png
  opendoc_logo_path: /assets/images/logo-full.png